runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

env_variables:
  HOLA_MUNDO: 'adios tonotos'
  DB_HOST: '/cloudsql/nube-2025-ii:us-central1:dbmendoza'
  DB_NAME: 'postgres'
  DB_USER: 'mendoza'
  DB_PASSWORD: 'V@.lery27890'

beta_settings:
  cloud_sql_instances: nube-2025-ii:us-central1:dbmendoza
